# Generated by Django 2.2.6 on 2019-10-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_auto_20191022_0335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='origin',
            field=models.CharField(choices=[('I', 'Industry - Professional from industry'), ('M', 'Academics - Professional from academy [student, master or PHD]')], max_length=1),
        ),
    ]
