# Generated by Django 2.2.6 on 2019-10-24 13:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_auto_20191022_1538'),
    ]

    operations = [
        migrations.CreateModel(
            name='DTModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgPath', models.CharField(max_length=50)),
                ('codeSnippet1', models.TextField()),
                ('codeSnippert2', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='sequenceNumber',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.CharField(choices=[('0-2', '0 to 2 years of experience'), ('3-5', '3 to 5 years of experience'), ('6-8', '6 to 8 years of experience'), ('MT9', 'More than 9 years of experience')], max_length=3, verbose_name='Programming experince'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='dtModel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.DTModel'),
            preserve_default=False,
        ),
    ]
