# Generated by Django 2.2.6 on 2019-10-26 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_auto_20191024_1306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='dtModel',
        ),
        migrations.AddField(
            model_name='answer',
            name='content',
            field=models.CharField(default='', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='dtModel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.DTModel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answer',
            name='task',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='tasks',
            field=models.ManyToManyField(to='questionnaire.Task'),
        ),
        migrations.AddField(
            model_name='task',
            name='questions',
            field=models.ManyToManyField(to='questionnaire.Question'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='experience',
            field=models.CharField(choices=[('0-2', '0 to 2 years of experience'), ('3-5', '3 to 5 years of experience'), ('6-8', '6 to 8 years of experience'), ('MT9', 'More than 9 years of experience')], max_length=3, verbose_name='Programming experience'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name (or Nickname)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.CharField(max_length=100),
        ),
    ]
