# Generated by Django 2.2.6 on 2019-10-26 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_auto_20191026_1325'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answer',
        ),
        migrations.AlterModelTable(
            name='dtmodel',
            table='dtModel',
        ),
        migrations.AlterModelTable(
            name='invitecontrol',
            table='inviteControl',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionnaire',
            table='questionnaire',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
    ]
