# Generated by Django 2.2.6 on 2019-10-26 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0007_auto_20191026_1340'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='ms_answer',
        ),
        migrations.AlterModelTable(
            name='dtmodel',
            table='ms_dtModel',
        ),
        migrations.AlterModelTable(
            name='invitecontrol',
            table='ms_inviteControl',
        ),
        migrations.AlterModelTable(
            name='participant',
            table='ms_participant',
        ),
        migrations.AlterModelTable(
            name='question',
            table='ms_question',
        ),
        migrations.AlterModelTable(
            name='questionnaire',
            table='ms_questionnaire',
        ),
        migrations.AlterModelTable(
            name='task',
            table='ms_task',
        ),
    ]
