# Generated by Django 2.2.6 on 2019-10-28 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_auto_20191028_1253'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shortName',
            field=models.CharField(default='', max_length=2, unique=True),
            preserve_default=False,
        ),
    ]
