# Generated by Django 2.2.6 on 2019-10-29 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0011_auto_20191028_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTaskCL',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.Answer')),
                ('answerq1', models.CharField(choices=[('CS', "It belongs to class 'Code smell'"), ('NC', "It DOESN'T belongs to class 'Code smell'")], max_length=2, verbose_name='')),
                ('answerq2', models.CharField(choices=[('VE', 'Very easy - I answered without any problems in less then 7 seconds'), ('E', 'Easy - I found the answer quite quickly and without major problems'), ('M', 'Medium'), ('D', 'Difficult - I had to think hard and am I am not sure if I answered correctly.'), ('VD', 'Very difficult - Despite thinking hard, my answer is likely to be wrong.')], max_length=2, verbose_name='')),
            ],
            bases=('questionnaire.answer',),
        ),
        migrations.RemoveField(
            model_name='answer',
            name='content',
        ),
    ]
