# Generated by Django 2.2.6 on 2019-10-29 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_auto_20191029_1406'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answertaskcl',
            table='ms_answerTaskCL',
        ),
    ]
