# Generated by Django 2.2.6 on 2019-10-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_auto_20191029_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='answerEndTime',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='answerStartTime',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='question',
        ),
        migrations.AddField(
            model_name='answer',
            name='secondsToAnswer',
            field=models.IntegerField(null=True),
        ),
    ]
