# Generated by Django 2.2.6 on 2019-10-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_auto_20191029_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaire',
            name='dtEndTasks',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='dtStartTasks',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
