# Generated by Django 2.2.6 on 2019-10-30 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_auto_20191029_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTaskID',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.Answer')),
                ('answerq1', models.CharField(choices=[('CDSBP', 'Class Data Should Be Private'), ('CC', 'Complex Class'), ('FE', 'Feature Envy'), ('GC', 'God Class'), ('II', 'Inappropriate Intimacy'), ('LC', 'Lazy Class'), ('LM', 'Long Method'), ('LPL', 'Long Parameter List'), ('MM', 'Middle Man'), ('RB', 'Refused Bequest'), ('SC', 'Spaghetti Code'), ('SG', 'Speculative Generality')], max_length=2, verbose_name='')),
            ],
            options={
                'db_table': 'ms_answerTaskID',
            },
            bases=('questionnaire.answer',),
        ),
        migrations.CreateModel(
            name='AnswerTaskRA',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.Answer')),
                ('answerq1', models.CharField(choices=[('VE', 'Very easily comprehensible'), ('E', 'Easily comprehensible'), ('C', 'Comprehensible'), ('D', 'Difficult to comprehend'), ('VD', 'Very difficult to comprehend')], max_length=2, verbose_name='')),
            ],
            options={
                'db_table': 'ms_answerTaskRA',
            },
            bases=('questionnaire.answer',),
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='sequenceNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='shortName',
            field=models.CharField(max_length=2),
        ),
    ]
