# Generated by Django 2.2.6 on 2019-10-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_auto_20191030_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sequenceNumber',
            field=models.IntegerField(null=True),
        ),
    ]
