# Generated by Django 2.2.6 on 2019-10-31 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0018_auto_20191030_1458'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='secondsToAnswer',
            field=models.FloatField(null=True),
        ),
    ]
