# Generated by Django 2.2.6 on 2019-11-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0021_auto_20191101_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertaskid',
            name='answerq1',
            field=models.CharField(choices=[('CDSBP', 'Class Data Should Be Private'), ('CC', 'Complex Class'), ('FE', 'Feature Envy'), ('GC', 'God Class'), ('II', 'Inappropriate Intimacy'), ('LC', 'Lazy Class'), ('LM', 'Long Method'), ('LPL', 'Long Parameter List'), ('MM', 'Middle Man'), ('RB', 'Refused Bequest'), ('SC', 'Spaghetti Code'), ('SG', 'Speculative Generality')], max_length=5, verbose_name=''),
        ),
    ]
