# Generated by Django 2.2.6 on 2019-11-06 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0022_auto_20191104_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='csBackground',
            field=models.CharField(choices=[('NK', 'Not knowledgeable (I do not know anything)'), ('SK', 'Somewhat knowledgeable (I have a vague idea)'), ('K', 'Knowledgeable (I am familiar with it)'), ('VK', 'Very knowledgeable (I know all/most classes and methods of it)')], default='K', max_length=2, verbose_name='Rate your background/knowledge about Code Smells'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='csdtBackground',
            field=models.CharField(choices=[('NK', 'Not knowledgeable (I do not know anything)'), ('SK', 'Somewhat knowledgeable (I have a vague idea)'), ('K', 'Knowledgeable (I am familiar with it)'), ('VK', 'Very knowledgeable (I know all/most classes and methods of it)')], default='K', max_length=2, verbose_name='Rate your background/knowledge about Code Smells Detection Tools'),
            preserve_default=False,
        ),
    ]
