# Generated by Django 2.2.6 on 2019-11-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0023_auto_20191106_0252'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='mlBackground',
            field=models.CharField(choices=[('NK', 'Not knowledgeable (I do not know anything)'), ('SK', 'Somewhat knowledgeable (I have a vague idea)'), ('K', 'Knowledgeable (I am familiar with it)'), ('VK', 'Very knowledgeable (I know all/most classes and methods of it)')], default='K', max_length=2, verbose_name='Rate your background/knowledge about machine learning and decision tree'),
            preserve_default=False,
        ),
    ]
