# Generated by Django 2.2.6 on 2019-11-12 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0027_auto_20191111_1212'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerTaskCC',
            fields=[
                ('answer_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='questionnaire.Answer')),
                ('answerq1', models.CharField(choices=[('HC', 'Highly Correlated - I detected a code smell in the showed code that matches the rules contained in the Decision Tree.'), ('LC', "Low Correlation -  I a detected a code smell in the showed code but I'm not sure wether the code smell type I've detected is the same code smell pointed in decision tree model."), ('NC', "I'ts not correlated / There isn't any correlation.")], default='', max_length=2, verbose_name='')),
                ('answerq1_complement', models.TextField(null=True)),
                ('answerq2', models.CharField(choices=[('HC', 'Highly Correlated - I detected a code smell in the showed code that matches the rules contained in the Decision Tree.'), ('LC', "Low Correlation -  I a detected a code smell in the showed code but I'm not sure wether the code smell type I've detected is the same code smell pointed in decision tree model."), ('NC', "I'ts not correlated / There isn't any correlation.")], default='', max_length=2, verbose_name='')),
                ('answerq2_complement', models.TextField(null=True)),
            ],
            options={
                'db_table': 'ms_answerTaskCC',
            },
            bases=('questionnaire.answer',),
        ),
        migrations.RemoveField(
            model_name='answertaskra',
            name='answer_ptr',
        ),
        migrations.RemoveField(
            model_name='answertaskid',
            name='answerq3',
        ),
        migrations.RemoveField(
            model_name='answertaskid',
            name='answerq3_complement',
        ),
        migrations.AlterField(
            model_name='answertaskid',
            name='answerq2',
            field=models.CharField(choices=[('VE', 'Very easily comprehensible'), ('E', 'Easily comprehensible'), ('C', 'Comprehensible'), ('D', 'Difficult to comprehend'), ('VD', 'Very difficult to comprehend')], default='', max_length=2, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answertaskid',
            name='answerq2_complement',
            field=models.TextField(verbose_name=''),
        ),
        migrations.DeleteModel(
            name='AnswerTaskCL',
        ),
        migrations.DeleteModel(
            name='AnswerTaskRA',
        ),
    ]
