# Generated by Django 2.2.6 on 2019-11-12 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0028_auto_20191112_0321'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='secondsToAnswer',
        ),
    ]
