# Generated by Django 2.2.6 on 2019-11-12 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0029_remove_answer_secondstoanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmodel',
            name='modelTreePath',
        ),
    ]
