# Generated by Django 2.2.6 on 2019-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0031_auto_20191112_0422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertaskid',
            name='answerq1_complement',
        ),
        migrations.RemoveField(
            model_name='answertaskid',
            name='answerq2_complement',
        ),
        migrations.AlterField(
            model_name='answertaskid',
            name='answerq2',
            field=models.IntegerField(choices=[(4, 'Very confident'), (3, 'Confident'), (2, 'A litle bit confident'), (1, 'Not confident at all')], verbose_name=''),
        ),
    ]
