# Generated by Django 2.2.6 on 2019-11-24 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0032_auto_20191123_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertaskcc',
            name='answerq1',
        ),
        migrations.RemoveField(
            model_name='answertaskcc',
            name='answerq1_complement',
        ),
        migrations.RemoveField(
            model_name='answertaskcc',
            name='answerq2',
        ),
        migrations.RemoveField(
            model_name='answertaskcc',
            name='answerq2_complement',
        ),
        migrations.AddField(
            model_name='answertaskcc',
            name='answer_cst',
            field=models.CharField(choices=[('CDSBP', 'Class Data Should Be Private'), ('CC', 'Complex Class'), ('FE', 'Feature Envy'), ('GC', 'God Class'), ('II', 'Inappropriate Intimacy'), ('LC', 'Lazy Class'), ('LM', 'Long Method'), ('LPL', 'Long Parameter List'), ('MM', 'Middle Man'), ('RB', 'Refused Bequest'), ('SC', 'Spaghetti Code'), ('SG', 'Speculative Generality')], default='CC', max_length=5, verbose_name=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertaskcc',
            name='answer_cst_confidence',
            field=models.IntegerField(choices=[(4, 'Very confident'), (3, 'Confident'), (2, 'A litle bit confident'), (1, 'Not confident at all')], verbose_name=''),
        ),
        migrations.AddField(
            model_name='answertaskcc',
            name='answer_cst_dm',
            field=models.IntegerField(choices=[(3, 'Very much'), (2, 'Not so much'), (1, 'None')], verbose_name=''),
        ),
        migrations.AddField(
            model_name='answertaskcc',
            name='answer_tr',
            field=models.IntegerField(choices=[(5, 'Very easily comprehensible'), (4, 'Easily comprehensible'), (3, 'Comprehensible'), (2, 'Difficult to comprehend'), (1, 'Very difficult to comprehend')], verbose_name=''),
        ),
        migrations.AddField(
            model_name='answertaskcc',
            name='answer_tr_complement',
            field=models.TextField(default='', verbose_name=''),
        ),
    ]
