# Generated by Django 2.2.6 on 2019-11-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0033_auto_20191124_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertaskid',
            name='answerq2',
            field=models.IntegerField(choices=[(4, 'Very confident'), (3, 'Confident'), (2, 'A litle bit confident'), (1, 'Not confident at all')], verbose_name=''),
        ),
    ]
