# Generated by Django 2.2.6 on 2019-11-24 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0034_auto_20191124_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answertaskid',
            old_name='answerq1',
            new_name='answer_cst',
        ),
        migrations.RemoveField(
            model_name='answertaskid',
            name='answerq2',
        ),
        migrations.AddField(
            model_name='answertaskid',
            name='answer_cst_confidence',
            field=models.IntegerField(choices=[(4, 'Very confident'), (3, 'Confident'), (2, 'A little bit confident'), (1, 'Not confident at all')], default=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answertaskcc',
            name='answer_cst_confidence',
            field=models.IntegerField(choices=[(4, 'Very confident'), (3, 'Confident'), (2, 'A little bit confident'), (1, 'Not confident at all')], default=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answertaskcc',
            name='answer_cst_dm',
            field=models.IntegerField(choices=[(3, 'Very much'), (2, 'Not so much'), (1, 'None')], default=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answertaskcc',
            name='answer_tr',
            field=models.IntegerField(choices=[(5, 'Very easily comprehensible'), (4, 'Easily comprehensible'), (3, 'Comprehensible'), (2, 'Difficult to comprehend'), (1, 'Very difficult to comprehend')], default=None, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='answertaskcc',
            name='answer_tr_complement',
            field=models.TextField(verbose_name=''),
        ),
    ]
