# Generated by Django 2.2.6 on 2019-11-25 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0035_auto_20191124_2032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dtmodel',
            old_name='codeSnippet1',
            new_name='codeSnippet',
        ),
        migrations.RenameField(
            model_name='dtmodel',
            old_name='imgPath',
            new_name='dtImg',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSnippet2',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='sequenceNumber',
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='codePSnippetProject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='codeSnippetKind',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='codeSnippetURI',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='dtDepth',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='dtNumberOfLeaves',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
