# Generated by Django 2.2.6 on 2019-12-05 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0040_auto_20191204_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSmellType',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSnippet',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSnippetKind',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSnippetProject',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='codeSnippetURI',
        ),
        migrations.RemoveField(
            model_name='dtmodel',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='task',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='sequenceNumber',
        ),
        migrations.RemoveField(
            model_name='task',
            name='shortName',
        ),
        migrations.AddField(
            model_name='dtmodel',
            name='task',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questionnaire.Task'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSmellScope',
            field=models.CharField(choices=[('C', 'Class'), ('M', 'Method')], default='C', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSmellType',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSnippetContent',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSnippetKind',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSnippetProject',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='task',
            name='codeSnippetURI',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
