# Generated by Django 2.2.6 on 2019-12-05 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0041_auto_20191205_0320'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='dtModel',
        ),
    ]
