# Generated by Django 2.2.6 on 2019-12-07 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0042_remove_answer_dtmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskGroup',
            field=models.IntegerField(choices=[(1, 'Group 1'), (2, 'Group 2')], default=0),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='LatinSquare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('column1Tasks', models.CharField(max_length=50)),
                ('column2Tasks', models.CharField(max_length=50)),
                ('row1Participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='questionnaire.Participant')),
                ('row2Participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='questionnaire.Participant')),
            ],
        ),
    ]
