# Generated by Django 2.2.6 on 2019-12-07 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0043_auto_20191207_1245'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='latinsquare',
            table='ms_latinSquare',
        ),
    ]
