# Generated by Django 2.2.6 on 2019-12-07 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0045_auto_20191207_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dtmodel',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='decisionTree',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.DTModel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='latinsquare',
            name='row1Participant',
            field=models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='participant1', to='questionnaire.Participant'),
        ),
        migrations.AlterField(
            model_name='latinsquare',
            name='row2Participant',
            field=models.OneToOneField(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='participant2', to='questionnaire.Participant'),
        ),
    ]
