# Generated by Django 2.2.6 on 2019-12-08 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0046_auto_20191207_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='secondsToAnswer',
            field=models.FloatField(null=True),
        ),
    ]
