# Generated by Django 2.2.6 on 2019-12-11 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0048_dtmodel_dtnodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='isDt',
            field=models.BooleanField(default=False),
        ),
    ]
