# Generated by Django 2.2.6 on 2019-12-12 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0049_answer_isdt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='decisionTree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='questionnaire.DTModel'),
        ),
    ]
