# Generated by Django 2.2.6 on 2019-12-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0050_auto_20191212_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answertaskid',
            name='answer_cst',
        ),
        migrations.RemoveField(
            model_name='answertaskid',
            name='answer_cst_confidence',
        ),
        migrations.AddField(
            model_name='answertaskid',
            name='answer_csagreement',
            field=models.IntegerField(choices=[(5, 'Strongly Agree'), (4, 'Agree'), (3, 'Undecided'), (2, 'Disagree'), (1, 'Strongly Disagree')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answertaskid',
            name='answer_description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AnswerTaskCC',
        ),
    ]
