# Generated by Django 2.2.6 on 2019-12-18 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0051_auto_20191218_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='secondsToAnswer',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='answertaskid',
            name='answer_csagreement',
            field=models.IntegerField(choices=[(2, 'Strongly Agree'), (1, 'Agree'), (0, 'Undecided'), (-1, 'Disagree'), (-2, 'Strongly Disagree')], default=''),
        ),
    ]
