# Generated by Django 2.2.6 on 2019-12-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0053_auto_20191219_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answertaskid',
            name='answer_csagreement',
            field=models.IntegerField(choices=[(2, 'Strongly Agree'), (1, 'Agree'), (-1, 'Disagree'), (-2, 'Strongly Disagree')], default=None),
        ),
    ]
