# Generated by Django 2.2.6 on 2019-12-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0054_auto_20191219_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='answertaskid',
            name='answer_dtDescription',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='answertaskid',
            name='answer_csagreement',
            field=models.IntegerField(choices=[(3, 'Agree Strongly'), (2, 'Agree Moderately'), (1, 'Agree Slightly'), (-1, 'Disagree Slightly'), (-2, 'Disagree Moderately'), (-3, 'Disagree Strongly')], default=None),
        ),
    ]
