# Generated by Django 2.2.6 on 2020-01-02 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0058_auto_20191230_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='isDummy',
            field=models.BooleanField(default=0),
        ),
    ]
