# Generated by Django 2.2.6 on 2020-01-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0059_task_isdummy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='dsDevelopmentExperience',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='dsIndustryRole',
        ),
        migrations.AddField(
            model_name='participant',
            name='origin',
            field=models.CharField(choices=[('I', 'Industry - Professional from industry.'), ('M', 'Academics - Professional from academy [student, master or PHD].'), ('B', 'Both - Professional from academy and industry.')], default='', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participant',
            name='yearsDevExperience',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeRevision_qtdProjects',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeRevision_qtdProjectsIndustry',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeRevision_qtdYears',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeSmellIdentification_qtdProjects',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeSmellIdentification_qtdProjectsIndustry',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='codeSmellIdentification_qtdYears',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='devExperience_qtdProjects',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='devExperience_qtdProjectsIndustry',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='devExperience_qtdYears',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='javaExperience_qtdProjects',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='javaExperience_qtdProjectsIndustry',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='javaExperience_qtdYears',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='objOrientedExperience_qtdProjects',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='objOrientedExperience_qtdProjectsIndustry',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='objOrientedExperience_qtdYears',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
    ]
