# Generated by Django 2.2.6 on 2020-01-07 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0060_auto_20200107_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='codeRevision_qtdProjects',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='codeRevision_qtdProjectsIndustry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='codeRevision_qtdYears',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='codeSmellIdentification_qtdProjects',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='codeSmellIdentification_qtdProjectsIndustry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='codeSmellIdentification_qtdYears',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='devExperience_qtdProjects',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='devExperience_qtdProjectsIndustry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='devExperience_qtdYears',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='javaExperience_qtdProjects',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='javaExperience_qtdProjectsIndustry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='javaExperience_qtdYears',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='objOrientedExperience_qtdProjects',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='objOrientedExperience_qtdProjectsIndustry',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='objOrientedExperience_qtdYears',
        ),
    ]
