# Generated by Django 2.2.6 on 2020-01-09 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0061_auto_20200107_1707'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='codeSnippet2Content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='codeSnippet2URI',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='degree',
            field=models.CharField(choices=[('B', 'Bachelor degree'), ('M', 'Master degree'), ('P', 'PHD'), ('N', 'None of them')], max_length=1),
        ),
        migrations.AlterField(
            model_name='participant',
            name='origin',
            field=models.CharField(choices=[('I', 'Industry - Professional from industry.'), ('A', 'Academy - Professional from academy [bacharelor, master or PHD].'), ('B', 'Both - Professional from academy and industry.')], max_length=1),
        ),
    ]
